config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

config/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('data/', views.tmdb, name='data'),
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail, name='detail'),

    # review
    path('<int:movie_id>/review_list/', views.review_list, name='review_list'),
    path('<int:movie_id>/review/create/', views.review_create, name='review_create'),
    path('<int:movie_id>/review/<int:review_id>/', views.review_detail, name='review_detail'),
    path('<int:movie_id>/review/<int:review_id>/update/', views.review_update, name='review_update'),
    path('<int:movie_id>/review/<int:review_id>/delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/review/<int:review_id>/like/', views.review_like, name='review_like'),
    
    # comment
    path('<int:movie_id>/review/<int:review_id>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:movie_id>/review/<int:review_id>/comment/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<int:movie_id>/review/<int:review_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    # oneline
    path('<int:movie_id>/oneline/', views.oneline_list, name='oneline_list'),
    path('<int:movie_id>/oneline/create/', views.oneline_create, name='oneline_create'),
    path('<int:movie_id>/oneline/<int:oneline_id>/update/', views.oneline_update, name='oneline_update'),
    path('<int:movie_id>/oneline/<int:oneline_id>/delete/', views.oneline_delete, name='oneline_delete'),
    path('<int:movie_id>/oneline/<int:oneline_id>/like/', views.oneline_like, name='oneline_like'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/', include('data.urls'))
]

config/movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    popularity = models.FloatField()
    video = models.BooleanField(default=False)
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    title = models.CharField(max_length=50)
    release_date = models.DateField()
    original_language = models.CharField(max_length=2)
    original_title = models.CharField(max_length=100)
    backdrop_path = models.TextField(blank=True, null=True)
    adult = models.BooleanField(default=False)
    overview = models.TextField()
    poster_path = models.TextField()
    

class Genre(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    movies = models.ManyToManyField(Movie, related_name='genres') # 중계모델


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_reviews')

    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')

    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

class Oneline(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='onelines')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_onelines')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_onelines')

    vote_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], default=0)
    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

config/movies/forms.py
from django import forms
from .models import Review, Comment, Oneline


class ReviewForm(forms.ModelForm):
    title=forms.CharField(
        label="제목",
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'제목을 작성해주세요.',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 작성해주세요.'
            }
        ),
    )

    class Meta:
        model = Review
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content',]


class OnelineForm(forms.ModelForm):
    content = forms.CharField(
        label='한줄평',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '한줄평을 남겨주세요.'
            }
        ),
    )

    RATING_NUMBERS = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
        (6,6),
        (7,7),
        (8,8),
        (9,9),
        (10,10),
    )

    vote_rating = forms.IntegerField(
        label='평점',
        widget=forms.Select(
            attrs={
                'class':'form-control'
            },
            choices=reversed(RATING_NUMBERS)
        ),
    )

    class Meta:
        model = Oneline
        fields = ['content', 'vote_rating']

config/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods ,require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q      
from django.http.response import JsonResponse

from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status

from .models import Movie, Genre, Review, Comment, Oneline
from .forms import ReviewForm, CommentForm, OnelineForm
from .serializers import ReviewSerializer, CommentSerializer, OnelineSerializer

import requests

from datetime import datetime



'''
추천 알고리즘 시작

################################################################
'''


today = ''
weather_movies = set()


def weather_recommand_genre_id_list():
    # api 요청
    params = {
        'lat': '35.1595454',
        'lon': '126.8526012',
        'appid': 'fb274443560bf75e3801324989c0959e',
        'lang': 'kr',
    }
    url = 'https://api.openweathermap.org/data/2.5/onecall'
    response = requests.get(url, params=params)
    data = response.json()
    weather_id = str(data["current"]["weather"][0]["id"])
    temp = data["current"]["temp"] - 273.15
    
    if weather_id[0] == '2':
        genres = [80, 27, 53, 9648,]
        # weather_id = '천둥치는'
    elif weather_id[0] == '3':
        genres = [80, 27, 53, 9648,]
        # weather_id = '이슬비 내리는'
    elif weather_id[0] == '5':
        genres = [80, 27, 53, 9648,]
        # weather_id = '비오는 '
    elif weather_id[0] == '6':
        genres = [10751, 18, 10770,]
        # weather_id = '소복소복 눈내리는'
    elif weather_id[0] == '7':
        genres = [37, 10752, 878, 36, 99]
        # weather_id = '먼지날리는'
    elif weather_id[0] == '8':
        # 맑은날씨
        if weather_id[2] == '0':
            if temp <= 0:
                genres = [28, 12, 35, 14, 10402, 10749]
            elif 0 < temp <= 15:
                genres = [28, 12, 35, 14, 10402, 10749]
            else:
                genres = [28, 12, 35, 14, 10402, 10749]
            # weather_id = '구름한점 없이 맑은'
        # 흐린날씨
        else:
            if temp <= 0:
                genres = [80, 27, 53, 9648,]
            elif 0 < temp <= 15:
                genres = [80, 27, 53, 9648,]
            else:
                genres = [80, 27, 53, 9648,]  
            # weather_id = '구름이 많은'
    return genres


'''
추천 알고리즘 끝

################################################################

영화 시작
'''


@login_required
@require_http_methods(['GET'])
def index(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()

    global today, weather_movies
    if today != datetime.today().strftime("%Y%m%d") or (not weather_movies and genres):
        today = datetime.today().strftime("%Y%m%d")
        for genre_id in weather_recommand_genre_id_list():
            weather_movies.update(set(get_object_or_404(Genre, id=genre_id).movies.all()))


    context = {
        'weather_movies': list(weather_movies),
        'movies': movies,
        'genres': genres,
    }
    return render(request, 'movies/index.html', context)


@login_required
@require_http_methods(['GET'])
def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


'''
영화 끝

################################################################

리뷰 시작
'''

@login_required
def review_list(request, movie_id):
    # articles = Article.objects.prefetch_related('like_users').select_related('user').annotate(likes=Count('like_users')).order_by('-pk')
    movie = get_object_or_404(Movie, id=movie_id)
    reviews = movie.reviews.all()
    form = ReviewForm()
    context = {
        'movie': movie,
        'reviews': reviews,
        'form': form,
    }
    return render(request, 'movies/review/list.html', context)


@api_view(['POST'])
def review_create(request, movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, id=movie_id)
        serializer = ReviewSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save(user=request.user, movie=movie)
            return Response({ 'data' : 'success!' })
    return redirect('accounts:login')


@login_required
def review_detail(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    review_form = ReviewForm(instance=review)
    comments = review.comments.all()
    comment_form = CommentForm()
    context = {
        'movie': movie,
        'review': review,
        'review_form': review_form,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'movies/review/detail.html', context)



@api_view(['POST'])
def review_update(request, movie_id, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, id=review_id)
        if request.user == review.user:
            movie = get_object_or_404(Movie, id=movie_id)
            serializer = ReviewSerializer(data=request.data, instance=review)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user, movie=movie)
                return Response({ 'data' : 'success!' })


@require_POST
def review_delete(request, movie_id, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, id=review_id)
        if request.user == review.user:
            review.delete()
            return redirect('movies:review_list', movie_id)

'''
리뷰 끝

################################################################

코멘트 시작
'''

@api_view(['POST'])
def comment_create(request, movie_id, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, id=review_id)
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            comment = serializer.save(user=request.user, review=review)
            return Response({'commentId': comment.id})


@api_view(['POST'])
def comment_update(request, movie_id, review_id, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user == comment.user:
            review = get_object_or_404(Review, id=review_id)
            serializer = CommentSerializer(data=request.data, instance=comment)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user, review=review)
                return Response({'commentId': comment.id})


@api_view(['POST'])
def comment_delete(request, movie_id, review_id, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user == comment.user:
            comment.delete()
            return Response({'commentId': comment.id})


'''
코멘트 끝

################################################################

한줄평 시작
'''

@login_required
def oneline_list(request, movie_id):
    # articles = Article.objects.prefetch_related('like_users').select_related('user').annotate(likes=Count('like_users')).order_by('-pk')
    form = OnelineForm()
    movie = get_object_or_404(Movie, id=movie_id)
    onelines = movie.onelines.all()
    context = {
        'movie': movie,
        'onelines': onelines,
        'form':form,
    }
    return render(request, 'movies/oneline/list.html', context)



@api_view(['POST'])
def oneline_create(request, movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, id=movie_id)
        serializer = OnelineSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save(user=request.user, movie=movie)
            
            vote_average = movie.vote_average
            vote_count = movie.vote_count

            vote_average = (vote_average * vote_count + serializer.data.get('vote_rating', 0)) / (vote_count + 1)
            vote_count += 1
            Movie.objects.filter(id=movie_id).update(vote_average=vote_average, vote_count=vote_count)

            return Response({ 'data' : 'success!' })


@api_view(['POST'])
def oneline_update(request, movie_id, oneline_id):
    if request.user.is_authenticated:
        oneline = get_object_or_404(Oneline, id=oneline_id)
        if request.user == oneline.user:
            movie = get_object_or_404(Movie, id=movie_id)
            serializer = OnelineSerializer(data=request.data, instance=oneline)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user, movie=movie)
                return Response({ 'data' : 'success!' })


@require_POST
def oneline_delete(request, movie_id, oneline_id):
    if request.user.is_authenticated:
        oneline = get_object_or_404(Oneline, id=oneline_id)
        if request.user == oneline.user:
            oneline.delete()
        return redirect('movies:oneline_list', movie_id)


'''
한줄평 끝

################################################################

좋아요 시작
'''


@api_view(['POST'])
def review_like(request, movie_id, review_id):
    if request.user.is_authenticated:
        like_status = request.data.get('like_status')
        user = request.user
        review = get_object_or_404(Review, id=review_id)
        if like_status:
            if review.like_users.filter(id=user.id).exists():
                review.like_users.remove(user)
                like_status = None
            else:
                review.like_users.add(user)
                if review.dislike_users.filter(id=user.id).exists():
                    review.dislike_users.remove(user)
        else:
            if review.dislike_users.filter(id=user.id).exists():
                review.dislike_users.remove(user)
                like_status = None
            else:

config/movies/templates/movies/review/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">리뷰 작성</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="{% url 'movies:review_list' movie_id %}">[back]</a>
{% endblock %}

config/movies/templates/movies/review/detail.html
{% extends 'base.html' %}

{% block content %}

<main>
<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <div><h1 class="display-4">상세리뷰</h1></div>
      <div class="row justify-content-end mb-3">
        <a href="{% url 'movies:index' %}">
          <button style="background-color:#590707; color:white;" type="button" class="btn mr-3 ">
            <span>뒤로가기</span>
            <i class="fas fa-arrow-left"></i>
          </button>
        </a>
      </div>

      <p class="lead">작성자 : {{ review.user.username }}</p>
      <p class="lead">글제목 : {{ review.title }}</p>
      <p class="lead">글내용 : {{ review.content }}</p>
      <p class="lead">작성일 : {{ review.created }}</p>
      <p class="lead">수정일 : {{ review.updated }}</p>
    </div>
    {% if user == review.user %}
    <div class="row ml-1">
      <!-- review_update -->
      <button style="background-color:#590707; color:white;"  type="button" class="oneline-create btn ml-3 mr-3" data-toggle="modal" data-target="#updateModal">
        <span>글 수정</span>
        <i class="fas fa-pen"></i>
      </button>
      
      <!-- review_delete -->
      <form action="{% url 'movies:review_delete' review.movie.id review.id %}" method="POST">
        {% csrf_token %}
        <button style="background-color:red;" class="btn btn-danger">삭제</button>
      </form>
    {% endif %}
    </div>
  </div>


  <!-- update Modal -->
  <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div style="background-color:#590707;" class="modal-header">
          <h5 style="color:white;" class="modal-title" id="exampleModalLabel">리뷰 수정</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
            <h1 class="text-center">리뷰</h1>
            <form id="review-update-form" action="" method="POST">
              {% csrf_token %}
              {{ review_form.as_p }}
              <div class="modal-footer">
                <button style="background-color:#590707;" type="button" class="btn btn-primary" id="review-update-button">수정</button>
                <button type="button" class="btn btn-dark" data-dismiss="modal">닫기</button>
              </div>
            </form>
        </div>

      </div>
    </div>
  </div>

  <hr>

  <!-- comment create -->
  <h1 class="text-light">댓글 작성</h1>
  <form class="text-light" id="comment-create-form" action="{% url 'movies:comment_create' review.movie.id review.id %}" method="POST">
    {% csrf_token %}
      {{ comment_form }}
      <input id="comment-create-button" type="submit">
  </form>
  <hr>

  <h1 class="text-light">댓글</h1>
  <div id="comment-list">
    {% for comment in comments %}
      <div id="comment-div-{{ comment.id }}" data-comment-id="{{ comment.id }}">
        <span class="text-light">{{ comment.content }}</span>
        {% if user == comment.user %}
          <button id="comment-update-button">수정</button>
          <button id="comment-delete-button">삭제</button>
        {% endif %}
      </div>
    {% endfor %}
  </div>
</div>
</main>
{% endblock %}


{% block script %}
  <script>

    const BASE_URL = `http://127.0.0.1:8000/movies/{{movie.id}}/review`
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    
    // review update
    const reviewUpdateButton = document.querySelector('#review-update-button')
    reviewUpdateButton.addEventListener('click', function (e) {
      e.preventDefault()

      const title = document.querySelector('input[name=title]').value
      const content = document.querySelector('textarea[name=content]').value
      const url = `${BASE_URL}/{{review.id}}/update/`

      axios({
        url: url,
        method: 'post',
        headers: { 'X-CSRFToken': csrftoken },
        data: {
          title: title, 
          content: content,
        }
      })
      .then(res => {
        console.log(res)
        window.location.reload()
      })
      .catch(err => {
        console.log(err)
        alert('글을 작성해주세요.')
      })

    })
  

    // comment
    const commentsList = document.querySelector('#comment-list')
    
    // comment delete
    function setCommentDelete(commentDeleteButton) {
      commentDeleteButton.addEventListener('click', e => {
        const commentId = e.target.parentElement.dataset.commentId
        const url = `${BASE_URL}/{{review.id}}/comment/${commentId}/delete/`

        axios({
          url: url,
          method: 'post',
          headers: { 'X-CSRFToken': csrftoken },
        })
        .then(res => {
          console.log(res)
          const commmentDiv = document.querySelector(`#comment-div-${commentId}`)
          commentsList.removeChild(commmentDiv)
        })
        .catch(err => {
          console.log(err)
        })
      })
    }
  
    const commentDeleteButtons = document.querySelectorAll('#comment-delete-button')
    commentDeleteButtons.forEach(commentDeleteButton => {
      setCommentDelete(commentDeleteButton)
    })

    // comment update
    function setCommentUpdate(commentUpdateButton) {
      commentUpdateButton.addEventListener('click', e => {
        const commentId = e.target.parentElement.dataset.commentId
        const url = `${BASE_URL}/{{review.id}}/comment/${commentId}/update/`
        // 기존의 태그들
        const commmentDiv = document.querySelector(`#comment-div-${commentId}`)
        const commentSpan = document.querySelector(`#comment-div-${commentId} > span`)
        const commentUpdateButton = document.querySelector(`#comment-div-${commentId} > #comment-update-button`)
        const commentDeleteButton = document.querySelector(`#comment-div-${commentId} > #comment-delete-button`)

        // 새로운 태그들
        const commentUpdateInput = document.createElement('input')
        commentUpdateInput.type = 'text'
        commentUpdateInput.value = commentSpan.innerText

        const commentUpdateCompleteButton = document.createElement('button')
        commentUpdateCompleteButton.innerText = '완료'
        commentUpdateCompleteButton.addEventListener('click', e => {
          const content = commentUpdateInput.value

          // 업데이트
          axios({
            url: url,
            method: 'post',
            headers: { 'X-CSRFToken': csrftoken },
            data: {
              content: content,
            }
          })
          .then(res => {
            console.log(res)
            // 업데이트
            commentSpan.innerText = content
            // 복구
            commmentDiv.innerHTML = ''
            commmentDiv.append(commentSpan, commentUpdateButton, commentDeleteButton)
          })
          .catch(err => {
            console.log(err)
          })
        })

        const commentUpdateCancelButton = document.createElement('button')
        commentUpdateCancelButton.innerText = '취소'
        commentUpdateCancelButton.addEventListener('click', e => {
          // 복구
          commmentDiv.innerHTML = ''
          commmentDiv.append(commentSpan, commentUpdateButton, commentDeleteButton)
        })

        // 새로운 태그들 추가
        commmentDiv.innerHTML = ''
        commmentDiv.append(commentUpdateInput, commentUpdateCompleteButton, commentUpdateCancelButton)
      })
    }
  
    const commentUpdateButtons = document.querySelectorAll('#comment-update-button')
    commentUpdateButtons.forEach(commentUpdateButton => {
      setCommentUpdate(commentUpdateButton)
    })

    const commentCreateButton = document.querySelector('#comment-create-button')
    commentCreateButton.addEventListener('click', function (e) {
      e.preventDefault()

      const commentInput = document.querySelector('#comment-create-form > input[name=content]')
      const content = commentInput.value
      const url = `${BASE_URL}/{{review.id}}/comment_create/`

      axios({
        url: url,
        method: 'post',
        headers: { 'X-CSRFToken': csrftoken },
        data: {
          content: content,
        }
      })
      .then(res => {
        console.log(res)
        const commentId = res.data.commentId

        const commentSpan = document.createElement('span')
        commentSpan.innerText = content
        commentInput.value = ''
        commentSpan.classList.add('text-light')
        
        const commentUpdateButton = document.createElement('button')
        commentUpdateButton.id = 'comment-update-button'
        commentUpdateButton.innerText = '수정'
        setCommentUpdate(commentUpdateButton)

        const commentDeleteButton = document.createElement('button')
        commentDeleteButton.id = 'comment-delete-button'
        commentDeleteButton.innerText = '삭제'
        setCommentDelete(commentDeleteButton)

        const commmentDiv = document.createElement('div')
        commmentDiv.id = `comment-div-${commentId}`
        commmentDiv.dataset.commentId = commentId
        commmentDiv.append(commentSpan, commentUpdateButton, commentDeleteButton)

        commentsList.append(commmentDiv)
      })
      .catch(err => {
        console.log(err)
        alert('글을 작성해주세요.')
      })
    })

  </script>
{% endblock %}

config/movies/templates/movies/review/update.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Movie Review Update</h1>
  <form action="{% url 'movies:review_update' review.movie.id review.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="#">[back]</a>
{% endblock %}