config/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/', include('data.urls'))
]

config/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

config/movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    popularity = models.FloatField()
    video = models.BooleanField(default=False)
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    title = models.CharField(max_length=50)
    release_date = models.DateField()
    original_language = models.CharField(max_length=2)
    original_title = models.CharField(max_length=100)
    backdrop_path = models.TextField(blank=True, null=True)
    adult = models.BooleanField(default=False)
    overview = models.TextField()
    poster_path = models.TextField()
    

class Genre(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    movies = models.ManyToManyField(Movie, related_name='genres') # 중계모델


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_reviews')

    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')

    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

class Oneline(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='onelines')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_onelines')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_onelines')

    vote_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], default=0)
    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

config/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms

class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['username', 'password']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control',
            })



class CustomUserChangeForm(UserChangeForm):

    password = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['email', 'first_name', 'last_name']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomPasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['old_password', 'new_password1', 'new_password2']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = get_user_model()
        fields = ('old_password', 'new_password1', 'new_password2',)


class CustomUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['email', 'password1', 'password2']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }

config/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth import get_user_model, update_session_auth_hash

from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status

from .forms import CustomUserChangeForm, CustomUserCreationForm, CustomLoginForm, CustomPasswordChangeForm
from .serializers import CustomUserChangeSerializer

# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
        
    if request.method == 'POST':
        form = CustomLoginForm(request, request.POST)
        if form.is_valid():
            # 로그인
            auth_login(request, form.get_user())
            print(request.GET.get('next'))
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = CustomLoginForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


@api_view(['POST'])
def update(request):
    if request.user.is_authenticated:
        serializer = CustomUserChangeSerializer(data=request.data, instance=request.user)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response({'data' : 'success'})


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('movies:index')


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile', request.user.username)
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

config/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/signup_and_login.css' %}">
{% endblock  %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-xs-12 col-md-8">
      <div class="login-box">
        <h1 class="text-light">비밀번호 변경</h1>
        <form class="d-flex flex-column" action="" method="POST">
          {% csrf_token %}
          {% for field in form %} 
            <div class="form-group m-3">
              <span>{{ field.errors }}</span>
              <span class="text-light">{{ field.label }}</span>
              <span>{{ field }}</span>
            </div>
          {% endfor %}
          <br>
          <input class="login-button btn mt-3 m-3" type="submit">
          <a href="{% url 'accounts:profile' user.username %}" class="btn btn-primary mt-3 m-3">뒤로가기</a>
        </form>
      </div>
    </div>
    <div class="col-2"></div>
  </div>
</div>
{% endblock %}

config/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/signup_and_login.css' %}">
{% endblock  %}


{% block content %}
<div class="box">
  <div class="container">
    <div class="row">
      <div class="col-2"></div>
      <div class="col-xs-12 col-md-8">
        <div class="login-box">
          <h1 class="text-light">로그인</h1>
          <form class="d-flex flex-column" action="" method="POST">
            {% csrf_token %}
            {% for field in form %} 
              <div class="form-group m-3">
                <span>{{ field.errors }}</span>
                <span class="text-light">{{ field.label }}</span>
                <span>{{ field }}</span>
              </div>
            {% endfor %}
            <br>
            <input class="login-button btn mt-3 m-3" type="submit">
          </form>
        </div>
      </div>
      <div class="col-2"></div>
    </div>
  </div>
</div>
{% endblock %}

config/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4">{{ person.username }}님의 프로필</h1>
  <p>{{ person.first_name }} {{ person.last_name }}</p>
  <hr class="my-4">
  <p class="lead">{{ person.email }}</p>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#userChangeModal">
    회원정보 수정
  </button>

  <!-- Modal -->
  <div class="modal fade" id="userChangeModal" tabindex="-1" aria-labelledby="userChangeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="userChangeModalLabel">회원정보 수정</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form>
            {% csrf_token %}
            <div class="form-group row">
              <label for="email-input" class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-10">
                <input id="email-input" type="email" class="form-control" value={{ person.email }}>
              </div>
            </div>

            <div class="form-row">
              <div class="col">
                <input id="first-name-input" type="text" class="form-control" placeholder="이름" value={{ person.first_name }}>
              </div>
              <div class="col">
                <input id="last-name-input" type="text" class="form-control" placeholder="성" value={{ person.last_name }}>
              </div>
            </div>
            
            <div class="modal-footer">
              <a class="btn btn-primary" href="{% url 'accounts:change_password' %}" role="button">비밀번호 변경</a>
              <button id="user-change-button" type="button" class="btn btn-primary">저장</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <hr>
  
  <h3>남긴 평점</h3>
  {% for oneline in person.oneline_set.all %}
    <ul>
      <li>{{ oneline.movie.title }} - {{ oneline.vote_rating }}</li>
    </ul>
  {% endfor %}
  <hr>
  <h3>작성한 리뷰</h3>
  {% for review in person.review_set.all %}
    <ul>
      <li>{{ review.title }}</li>
    </ul>
  {% endfor %}
  <hr>
  <h3>작성한 댓글</h3>
  {% for comment in person.comment_set.all %}
    <ul>
      <li>{{ comment.content }}</li>
    </ul>
  {% endfor %}
  <hr>
</div>

{% endblock  %}

{% block script %}
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  const userChangeButton = document.querySelector('#user-change-button')
  userChangeButton.addEventListener('click', e => {
    e.preventDefault()
    console.log(e)

    const email = document.querySelector('#email-input').value
    const first_name = document.querySelector('#first-name-input').value
    const last_name = document.querySelector('#last-name-input').value

    const url = `http://127.0.0.1:8000/accounts/update/`

    axios({
      url: url,
      method: 'post',
      headers: { 'X-CSRFToken': csrftoken },
      data: {
        email: email, 
        first_name: first_name,
        last_name: last_name,
      }
    })
    .then(res => {
      console.log(res)
      window.location.reload()
    })
    .catch(err => {
      console.log(err)
    })
  })
</script>
{% endblock  %}

config/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/signup_and_login.css' %}">
{% endblock  %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-xs-12 col-md-8">
      <div class="login-box">
        <h1 class="text-light">회원가입</h1>
        <form class="d-flex flex-column" action="" method="POST">
          {% csrf_token %}
          {% for field in form %} 
            <div class="form-group m-3">
              <span>{{ field.errors }}</span>
              <span class="text-light">{{ field.label }}</span>
              <span>{{ field }}</span>
            </div>
          {% endfor %}
          <br>
          <input class="signup-button btn mt-3 m-3" type="submit">
        </form>
      </div>
    </div>
    <div class="col-2"></div>
  </div>
</div>
{% endblock %}

config/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block authentication_style %}
  <link rel="stylesheet" href="{% static 'css/authentication_style.css' %}">
{% endblock  %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-xs-12 col-md-8">
      <div class="login-box">
        <h1 class="text-monospace">회원정보 수정</h1>
        <form class="d-flex flex-column" action="" method="POST">
          {% csrf_token %}
          {% for field in form %} 
            <div class="form-group">
              <span>{{ field.errors }}</span>
              {{ field.label }}
              {{ field }}

            </div>
          {% endfor %}
          <a class="mt-3 btn login-button" href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
          <br>
          <input class="login-button btn mt-3" type="submit">
        </form>
      </div>
    </div>
    <div class="col-2"></div>
  </div>
</div>
{% endblock %}