config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

config/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('data/', views.tmdb, name='data'),
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail, name='detail'),

    # review
    path('<int:movie_id>/review_list/', views.review_list, name='review_list'),
    path('<int:movie_id>/review/create/', views.review_create, name='review_create'),
    path('<int:movie_id>/review/<int:review_id>/', views.review_detail, name='review_detail'),
    path('<int:movie_id>/review/<int:review_id>/update/', views.review_update, name='review_update'),
    path('<int:movie_id>/review/<int:review_id>/delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/review/<int:review_id>/like/', views.review_like, name='review_like'),
    
    # comment
    path('<int:movie_id>/review/<int:review_id>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:movie_id>/review/<int:review_id>/comment/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<int:movie_id>/review/<int:review_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    # oneline
    path('<int:movie_id>/oneline/', views.oneline_list, name='oneline_list'),
    path('<int:movie_id>/oneline/create/', views.oneline_create, name='oneline_create'),
    path('<int:movie_id>/oneline/<int:oneline_id>/update/', views.oneline_update, name='oneline_update'),
    path('<int:movie_id>/oneline/<int:oneline_id>/delete/', views.oneline_delete, name='oneline_delete'),
    path('<int:movie_id>/oneline/<int:oneline_id>/like/', views.oneline_like, name='oneline_like'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/', include('data.urls'))
]

config/movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    popularity = models.FloatField()
    video = models.BooleanField(default=False)
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    title = models.CharField(max_length=50)
    release_date = models.DateField()
    original_language = models.CharField(max_length=2)
    original_title = models.CharField(max_length=100)
    backdrop_path = models.TextField(blank=True, null=True)
    adult = models.BooleanField(default=False)
    overview = models.TextField()
    poster_path = models.TextField()
    

class Genre(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    movies = models.ManyToManyField(Movie, related_name='genres') # 중계모델


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_reviews')

    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')

    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

class Oneline(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='onelines')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_onelines')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_onelines')

    vote_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], default=0)
    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

config/movies/forms.py
from django import forms
from .models import Review, Comment, Oneline


class ReviewForm(forms.ModelForm):
    title=forms.CharField(
        label="제목",
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'제목을 작성해주세요.',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 작성해주세요.'
            }
        ),
    )

    class Meta:
        model = Review
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content',]


class OnelineForm(forms.ModelForm):
    content = forms.CharField(
        label='한줄평',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '한줄평을 남겨주세요.'
            }
        ),
    )

    RATING_NUMBERS = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
        (6,6),
        (7,7),
        (8,8),
        (9,9),
        (10,10),
    )

    vote_rating = forms.IntegerField(
        label='평점',
        widget=forms.Select(
            attrs={
                'class':'form-control'
            },
            choices=reversed(RATING_NUMBERS)
        ),
    )

    class Meta:
        model = Oneline
        fields = ['content', 'vote_rating']

config/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods ,require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q      
from django.http.response import JsonResponse

from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status

from .models import Movie, Genre, Review, Comment, Oneline
from .forms import ReviewForm, CommentForm, OnelineForm
from .serializers import ReviewSerializer, CommentSerializer, OnelineSerializer

import requests

from datetime import datetime



'''
추천 알고리즘 시작

################################################################
'''


today = ''
weather_movies = set()


def weather_recommand_genre_id_list():
    # api 요청
    params = {
        'lat': '35.1595454',
        'lon': '126.8526012',
        'appid': 'fb274443560bf75e3801324989c0959e',
        'lang': 'kr',
    }
    url = 'https://api.openweathermap.org/data/2.5/onecall'
    response = requests.get(url, params=params)
    data = response.json()
    weather_id = str(data["current"]["weather"][0]["id"])
    temp = data["current"]["temp"] - 273.15
    
    if weather_id[0] == '2':
        genres = [80, 27, 53, 9648,]
        # weather_id = '천둥치는'
    elif weather_id[0] == '3':
        genres = [80, 27, 53, 9648,]
        # weather_id = '이슬비 내리는'
    elif weather_id[0] == '5':
        genres = [80, 27, 53, 9648,]
        # weather_id = '비오는 '
    elif weather_id[0] == '6':
        genres = [10751, 18, 10770,]
        # weather_id = '소복소복 눈내리는'
    elif weather_id[0] == '7':
        genres = [37, 10752, 878, 36, 99]
        # weather_id = '먼지날리는'
    elif weather_id[0] == '8':
        # 맑은날씨
        if weather_id[2] == '0':
            if temp <= 0:
                genres = [28, 12, 35, 14, 10402, 10749]
            elif 0 < temp <= 15:
                genres = [28, 12, 35, 14, 10402, 10749]
            else:
                genres = [28, 12, 35, 14, 10402, 10749]
            # weather_id = '구름한점 없이 맑은'
        # 흐린날씨
        else:
            if temp <= 0:
                genres = [80, 27, 53, 9648,]
            elif 0 < temp <= 15:
                genres = [80, 27, 53, 9648,]
            else:
                genres = [80, 27, 53, 9648,]  
            # weather_id = '구름이 많은'
    return genres


'''
추천 알고리즘 끝

################################################################

영화 시작
'''


@login_required
@require_http_methods(['GET'])
def index(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()

    global today, weather_movies
    if today != datetime.today().strftime("%Y%m%d") or (not weather_movies and genres):
        today = datetime.today().strftime("%Y%m%d")
        for genre_id in weather_recommand_genre_id_list():
            weather_movies.update(set(get_object_or_404(Genre, id=genre_id).movies.all()))


    context = {
        'weather_movies': list(weather_movies),
        'movies': movies,
        'genres': genres,
    }
    return render(request, 'movies/index.html', context)


@login_required
@require_http_methods(['GET'])
def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


'''
영화 끝

################################################################

리뷰 시작
'''

@login_required
def review_list(request, movie_id):
    # articles = Article.objects.prefetch_related('like_users').select_related('user').annotate(likes=Count('like_users')).order_by('-pk')
    movie = get_object_or_404(Movie, id=movie_id)
    reviews = movie.reviews.all()
    form = ReviewForm()
    context = {
        'movie': movie,
        'reviews': reviews,
        'form': form,
    }
    return render(request, 'movies/review/list.html', context)


@api_view(['POST'])
def review_create(request, movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, id=movie_id)
        serializer = ReviewSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save(user=request.user, movie=movie)
            return Response({ 'data' : 'success!' })
    return redirect('accounts:login')


@login_required
def review_detail(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    review_form = ReviewForm(instance=review)
    comments = review.comments.all()
    comment_form = CommentForm()
    context = {
        'movie': movie,
        'review': review,
        'review_form': review_form,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'movies/review/detail.html', context)



@api_view(['POST'])
def review_update(request, movie_id, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, id=review_id)
        if request.user == review.user:
            movie = get_object_or_404(Movie, id=movie_id)
            serializer = ReviewSerializer(data=request.data, instance=review)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user, movie=movie)
                return Response({ 'data' : 'success!' })


@require_POST
def review_delete(request, movie_id, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, id=review_id)
        if request.user == review.user:
            review.delete()
            return redirect('movies:review_list', movie_id)

'''
리뷰 끝

################################################################

코멘트 시작
'''

@api_view(['POST'])
def comment_create(request, movie_id, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, id=review_id)
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            comment = serializer.save(user=request.user, review=review)
            return Response({'commentId': comment.id})


@api_view(['POST'])
def comment_update(request, movie_id, review_id, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user == comment.user:
            review = get_object_or_404(Review, id=review_id)
            serializer = CommentSerializer(data=request.data, instance=comment)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user, review=review)
                return Response({'commentId': comment.id})


@api_view(['POST'])
def comment_delete(request, movie_id, review_id, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user == comment.user:
            comment.delete()
            return Response({'commentId': comment.id})


'''
코멘트 끝

################################################################

한줄평 시작
'''

@login_required
def oneline_list(request, movie_id):
    # articles = Article.objects.prefetch_related('like_users').select_related('user').annotate(likes=Count('like_users')).order_by('-pk')
    form = OnelineForm()
    movie = get_object_or_404(Movie, id=movie_id)
    onelines = movie.onelines.all()
    context = {
        'movie': movie,
        'onelines': onelines,
        'form':form,
    }
    return render(request, 'movies/oneline/list.html', context)



@api_view(['POST'])
def oneline_create(request, movie_id):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, id=movie_id)
        serializer = OnelineSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save(user=request.user, movie=movie)
            
            vote_average = movie.vote_average
            vote_count = movie.vote_count

            vote_average = (vote_average * vote_count + serializer.data.get('vote_rating', 0)) / (vote_count + 1)
            vote_count += 1
            Movie.objects.filter(id=movie_id).update(vote_average=vote_average, vote_count=vote_count)

            return Response({ 'data' : 'success!' })


@api_view(['POST'])
def oneline_update(request, movie_id, oneline_id):
    if request.user.is_authenticated:
        oneline = get_object_or_404(Oneline, id=oneline_id)
        if request.user == oneline.user:
            movie = get_object_or_404(Movie, id=movie_id)
            serializer = OnelineSerializer(data=request.data, instance=oneline)
            if serializer.is_valid(raise_exception=True):
                serializer.save(user=request.user, movie=movie)
                return Response({ 'data' : 'success!' })


@require_POST
def oneline_delete(request, movie_id, oneline_id):
    if request.user.is_authenticated:
        oneline = get_object_or_404(Oneline, id=oneline_id)
        if request.user == oneline.user:
            oneline.delete()
        return redirect('movies:oneline_list', movie_id)


'''
한줄평 끝

################################################################

좋아요 시작
'''


@api_view(['POST'])
def review_like(request, movie_id, review_id):
    if request.user.is_authenticated:
        like_status = request.data.get('like_status')
        user = request.user
        review = get_object_or_404(Review, id=review_id)
        if like_status:
            if review.like_users.filter(id=user.id).exists():
                review.like_users.remove(user)
                like_status = None
            else:
                review.like_users.add(user)
                if review.dislike_users.filter(id=user.id).exists():
                    review.dislike_users.remove(user)
        else:
            if review.dislike_users.filter(id=user.id).exists():
                review.dislike_users.remove(user)
                like_status = None
            else:

config/movies/templates/movies/oneline/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Oneline Create</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="{% url 'movies:oneline_list' movie_id %}">[back]</a>
{% endblock %}

config/movies/templates/movies/oneline/list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'css/oneline_review.css' %}">
{% endblock %}

{% block content %}
  <main>
    <div class="container">
      <div><h1 class="text-light">한줄평</h1></div>
      <div class="row justify-content-end mb-3">
        <button style="background-color:#590707; color:white;"  type="button" class="oneline-create btn mr-3" data-toggle="modal" data-target="#createModal">
          <span>글작성</span>
          <i class="fas fa-pen"></i>
        </button>
        <a href="{% url 'movies:index' %}">
          <button style="background-color:#590707; color:white;" type="button" class="btn mr-3 ">
            <span>뒤로가기</span>
            <i class="fas fa-arrow-left"></i>
          </button>
        </a>
      </div>
      <div style="border-radius:10px;" class="bg-light">
        {% if onelines %}
        <ul class="score_result p-3">
          {% for oneline in onelines %}
            <li class="row">
              <div class="col-2">
                {% if 1 <=  oneline.vote_rating and oneline.vote_rating <= 2 %}
                  <span>★☆☆☆☆</span>
                {% elif 3 <=  oneline.vote_rating and oneline.vote_rating <= 4 %}
                  <span>★★☆☆☆</span>
                {% elif 5 <=  oneline.vote_rating and oneline.vote_rating <= 6 %}
                  <span>★★★☆☆</span>
                {% elif 7 <=  oneline.vote_rating and oneline.vote_rating <= 8 %}
                  <span>★★★★☆</span>
                {% else %}
                  <span>★★★★★</span>
                {% endif %}
                <span><em>{{ oneline.vote_rating }}</em></span>
              </div>
              <div class="col-6">
                <span>{{ oneline.content }}</span>
                <dl>
                  <dt>
                    <em><span>{{ oneline.user }} | </span></em>
                    <em>{{ oneline.created }}</em>
                  </dt>
                </dl>
              </div>
              {% if request.user == oneline.user %}
              <div class="col-2">
                <div class="row">
                  <!-- 한줄평 수정버튼 -->
                  <form action="{% url 'movies:oneline_delete' oneline.movie.id oneline.id %}" method="POST">
                    {% csrf_token %}
                    <button type="button" data-toggle="modal" data-target="#updateModal{{ oneline.id }}">
                      <i class="fas fa-edit"></i>
                    </button>
                  </form>
                  <!-- 한줄평 삭제버튼 -->
                  <form action="{% url 'movies:oneline_delete' oneline.movie.id oneline.id %}" method="POST">
                    {% csrf_token %}
                    <button>
                      <i class="fas fa-trash-alt"></i>
                    </button>
                  </form>
                </div>
              </div>
              {% endif %}
              <div class="col-2">
                <button id="oneline-like-button" class="btn btn-primary" data-oneline-id="{{ oneline.id }}">
                  {% if user in oneline.like_users.all %}
                    <i id="thumbs-up-{{ oneline.id }}" class="fas fa-thumbs-up">{{ oneline.like_users.count }}</i>
                  {% else %}
                    <i id="thumbs-up-{{ oneline.id }}" class="far fa-thumbs-up">{{ oneline.like_users.count }}</i>
                  {% endif %}
                </button>
                <button id="oneline-dislike-button" class="btn btn-danger" data-oneline-id="{{ oneline.id }}">
                  {% if user in oneline.dislike_users.all %}
                    <i id="thumbs-down-{{ oneline.id }}" class="fas fa-thumbs-down">{{ oneline.dislike_users.count }}</i>
                  {% else %}
                    <i id="thumbs-down-{{ oneline.id }}" class="far fa-thumbs-down">{{ oneline.dislike_users.count }}</i>
                  {% endif %}
                </button>
              </div>

              <hr style="border-top:3px dotted;">
            </li>
            <hr>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
    </div>
  </main>
<hr>





  <!-- Create Modal -->
  <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">한줄평 작성</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="" method="POST">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group m-3">
                  <span>{{ field.errors }}</span>
                  <span class="">{{ field.label }}</span>
                  <span>{{ field }}</span>
                </div>
              {% endfor %}
              <div class="container">
                <div class="row justify-content-end p-3">
                  <button style="background-color:#590707" id="create-button" type="button" class="btn btn-primary">저장</button>
                  <button type="button" class="btn btn-dark ml-1" data-dismiss="modal">닫기</button>
                </div>
              </div>
            </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

  <!-- Update Modal -->
  {% for oneline in onelines %}
    <div class="modal fade" id="updateModal{{ oneline.id }}" tabindex="-1" aria-labelledby="updateModalLabel{{ oneline.id }}" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="updateModalLabel{{ oneline.id }}">한줄평 수정</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mt-3">
            <form action="" method="POST" id="{{ oneline.id }}">
              {% csrf_token %}
              <label for="update-content-{{ oneline.id }}">한줄평</label>
              <input id="update-content-{{ oneline.id }}" value="{{ oneline.content }}" class="form-control" type="text" placeholder="Default input">
              <br>
              <label for="update-vote-rating-{{ oneline.id }}">평점 </label>
              <select class="custom-select mb-3" id="update-vote-rating-{{ oneline.id }}">
                <option selected disabled >{{ oneline.vote_rating }}</option>
                <option value="10">10</option>
                <option value="9">9</option>
                <option value="8">8</option>
                <option value="7">7</option>
                <option value="6">6</option>
                <option value="5">5</option>
                <option value="4">4</option>
                <option value="3">3</option>
                <option value="2">2</option>
                <option value="1">1</option>
              </select>
              <hr>
              <input id="update-button" type="submit" class="btn btn-secondary" value="저장">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock %}


{% block script %}
  <script>
    // 한줄평 생성 버튼
    const BASE_URL = `http://127.0.0.1:8000/movies/{{movie.id}}/oneline`
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    
    const createButton = document.querySelector('#create-button')
    createButton.addEventListener('click', function(e) {
      e.preventDefault()
      const content = document.querySelector('input[name=content]').value
      const vote_rating = document.querySelector('select[name=vote_rating]').value
      const url = `${BASE_URL}/create/`
      
      axios({
        url: url,
        method: 'post',
        headers: { 'X-CSRFToken': csrftoken },
        data: {
          content: content,
          vote_rating: vote_rating 
        }
      })
      .then(res => {
        console.log(res)
        window.location.reload()
      })
      .catch(err => {
        console.log(err)
        alert('글을 작성해주세요.')
      })

    })

    // 한줄평 수정 버튼
    const updateButtons = document.querySelectorAll('#update-button')
    updateButtons.forEach(updateButton => {
      updateButton.addEventListener('click', function (e) {
        e.preventDefault()

        const onelineId = e.target.parentElement.id
        const content = document.querySelector(`#update-content-${onelineId}`).value
        const vote_rating = document.querySelector(`#update-vote-rating-${onelineId}`).value
        const url = `${BASE_URL}/${onelineId}/update/`

        axios({
          url: url,
          method: 'post',
          headers: { 'X-CSRFToken': csrftoken },
          data: {
            content: content,
            vote_rating: vote_rating 
          },
        })
        .then(res => {
          console.log(res)
          window.location.reload()
        })
        .catch(err => {
          console.log(err)
          alert('글을 작성해주세요.')
        })
      })
    })

    // 좋아요 버튼
    const onelineLikeButtons = document.querySelectorAll('#oneline-like-button')
    onelineLikeButtons.forEach(onelineLikeButton => {
      onelineLikeButton.addEventListener('click', e => {
        e.preventDefault()
        const onelineId = e.target.dataset.onelineId
        const URL=`${BASE_URL}/${onelineId}/like/`
        axios({
        url: URL,
        method: 'post',
        headers: { 'X-CSRFToken': csrftoken },
        data: {
          like_status: true,
        },
        })
        .then(res => {
          console.log(res)
          const { like_status, like_count, dislike_count } = res.data
          const faThumbsUp = document.querySelector(`#thumbs-up-${onelineId}`)
          const faThumbsDown = document.querySelector(`#thumbs-down-${onelineId}`)
          if (like_status) {
            faThumbsUp.classList.add('fas')
            faThumbsUp.classList.remove('far')

            faThumbsDown.classList.add('far')
            faThumbsDown.classList.remove('fas')
          } else {
            faThumbsUp.classList.add('far')
            faThumbsUp.classList.remove('fas')
          }
          faThumbsUp.innerText = like_count
          faThumbsDown.innerText = dislike_count
        })
        .catch(err => {
          console.log(err)
        })
      })
    })
    
    
    // 싫어요 버튼
    const onelineDislikeButtons = document.querySelectorAll('#oneline-dislike-button')
    onelineDislikeButtons.forEach(onelineDislikeButton => {
      onelineDislikeButton.addEventListener('click', e => {
        e.preventDefault()
        const onelineId = e.target.dataset.onelineId
        const URL=`${BASE_URL}/${onelineId}/like/`
        axios({
        url: URL,
        method: 'post',
        headers: { 'X-CSRFToken': csrftoken },
        data: {
          like_status: false,
        },
        })
        .then(res => {
          console.log(res)
          const { like_status, like_count, dislike_count } = res.data
          const faThumbsUp = document.querySelector(`#thumbs-up-${onelineId}`)
          const faThumbsDown = document.querySelector(`#thumbs-down-${onelineId}`)
          if (like_status === false) {
            faThumbsDown.classList.add('fas')
            faThumbsDown.classList.remove('far')

            faThumbsUp.classList.add('far')
            faThumbsUp.classList.remove('fas')
          } else {
            faThumbsDown.classList.add('far')
            faThumbsDown.classList.remove('fas')
          }
          faThumbsUp.innerText = like_count
          faThumbsDown.innerText = dislike_count
        })
        .catch(err => {
          console.log(err)
        })
      })
    })
  </script>
{% endblock %}

config/movies/templates/movies/oneline/update.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Oneline Update</h1>
  <form action="{% url 'movies:review_update' review.movie.id review.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="#">[back]</a>
{% endblock %}